#直接从config.xlsx excel表格拷贝过来，非常方便，在excel编辑也非常方便
ThisDeviceType	0
  #	id	sub_id	name	width	height	price	image_path1	image_sub_path2
Building	11	1	盟军发电厂	2	2	500	1-主建筑	1-发电厂
Building	11	2	盟军矿厂	2	2	2000	1-主建筑	2-矿厂
Building	11	3	盟军兵工厂	2	2	500	1-主建筑	3-兵工厂
Building	11	4	盟军重工	2	2	2000	1-主建筑	4-盟军重工
Building	11	5	雷达	2	2	2000	1-主建筑	5-雷达
Building	11	6	盟军空指部	2	2	2000	1-主建筑	5-盟军空指部
Building	11	7	盟军作战实验室	2	2	2000	1-主建筑	7-盟军作战实验室
Building	11	8	盟军船厂	3	3	2000	1-主建筑	9-盟军船厂
Building	12	1	盟军围墙	2	2	100	2-防御建筑	1-盟军围墙
Building	12	2	盟军机枪碉堡	2	2	100	2-防御建筑	2-盟军机枪碉堡
Building	12	3	盟军防空炮	2	2	100	2-防御建筑	3-盟军防空炮
SeaUnit	24	6	驱逐舰	2	2	500	5-船厂兵种	2-盟军-驱逐舰
SeaUnit	24	7	两栖运输船	2	2	500	5-船厂兵种	1-盟军-两栖运输船
LandUnit	33	1	动员兵	1	1	100	3-兵营兵种	1-动员兵
LandUnit	33	2	工程师	1	1	100	3-兵营兵种	2-工程师
LandUnit	33	3	警犬	1	1	200	3-兵营兵种	3-警犬
LandUnit	34	1	武装矿车	2	2	1400	4-重工兵种	1-武装矿车
LandUnit	34	2	灰熊坦克	2	2	700	4-重工兵种	2-灰熊坦克
LandUnit	34	3	犀牛坦克	2	2	900	4-重工兵种	2-犀牛坦克
LandUnit	34	4	盟军防空车	2	2	600	4-重工兵种	3-防空车
LandUnit	34	6	盟军基地车	3	3	3000	1-主建筑	盟军基地
AirUnit	43	4	火箭飞行兵	1	1	500	3-兵营兵种	4-火箭飞行兵
AirUnit	44	5	直升机	2	2	1500	4-重工兵种	4-直升机
